import { getSession, signIn, signOut, createQuestion } from './supabase-api.js';

const contentKey='ts-hepa-content-v2',sessionsKey='ts-hepa-sessions-v2';
const seed={theme:'Essais des filtres THE/HEPA',chapters:[{id:'the',title:'Principes des filtres THE',quiz:{title:'Quiz — Principes THE',questions:[{id:'q1',body:'Quel est l’objectif principal d’un filtre THE/HEPA ?',seconds:30,answers:['Réduire le bruit','Retenir les particules ciblées','Augmenter le débit','Refroidir le local'],correct:1,explanation:'Le filtre retient les particules ciblées afin de limiter la contamination.'},{id:'q2',body:'Quel élément doit être relevé pour la traçabilité ?',seconds:25,answers:['La référence du filtre','La couleur du local','Le nom du visiteur','Le niveau sonore'],correct:0,explanation:'La référence permet le suivi des essais.'}]}},{id:'integrity',title:'Essais d’intégrité',quiz:{title:'Quiz — Essais d’intégrité',questions:[{id:'q3',body:'Pourquoi réalise-t-on un essai d’intégrité après installation ?',seconds:35,answers:['Vérifier la couleur du cadre','Détecter les fuites du média ou du montage','Mesurer uniquement la température','Nettoyer le caisson'],correct:1,explanation:'L’essai recherche une fuite du média filtrant ou de son montage.'},{id:'q4',body:'Qui pilote le passage à la question suivante ?',seconds:20,answers:['Chaque apprenant','Le dernier répondant','L’instructeur','Le superadmin uniquement'],correct:2,explanation:'L’instructeur garde la maîtrise du rythme de la session.'}]}}]};
let data=JSON.parse(localStorage.getItem(contentKey)||'null')||seed,sessions=JSON.parse(localStorage.getItem(sessionsKey)||'null')||[],activeSession=null,learnerName='',answerChoice=null,timer=null;
const app=document.querySelector('#app'),bus=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('ts-hepa-live'):null;
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{localStorage.setItem(contentKey,JSON.stringify(data));localStorage.setItem(sessionsKey,JSON.stringify(sessions));bus?.postMessage('update')};
const sessionByCode=code=>sessions.find(s=>s.code===code?.toUpperCase()),quizFor=s=>data.chapters.find(c=>c.id===s.chapterId)?.quiz;
const appUrl=location.protocol==='file:'?'http://localhost:5173/index.html':`${location.origin}${location.pathname}`;
const sessionUrl=code=>`${appUrl}?session=${encodeURIComponent(code)}`;
const code=()=>`THE${Math.random().toString(36).slice(2,5).toUpperCase()}`;
const qr=key=>`https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=10&data=${encodeURIComponent(sessionUrl(key))}`;
function layout(body){app.innerHTML=`<div class="app"><header class="topbar"><button class="brand" onclick="openView('landing')"><span class="logo">TS</span><span>Formation <small>· Quiz THE/HEPA</small></span></button><nav class="top-actions"><button class="link-button" onclick="openView('instructor')">Instructeur</button><button class="link-button" onclick="openView('admin')">Administration</button></nav></header><main class="container">${body}</main></div>`}
function openView(v){clearInterval(timer);({landing,join,waiting,learnerQuiz,instructor,admin}[v]||landing)()}
function landing(){layout(`<section><p class="eyebrow">Formation interactive</p><h1>Scannez le QR code pour rejoindre votre session.</h1><p class="lead">L’instructeur prépare une session puis partage le QR code généré automatiquement. Les apprenants saisissent leur nom et prénom avant d’entrer dans la salle d’attente.</p><div class="grid three"><button class="choice" onclick="openView('join')"><span class="choice-icon">⌁</span><span class="tag">Apprenant</span><h2>J’ai un QR code</h2><p class="muted">Rejoindre une session en direct.</p></button><button class="choice" onclick="openView('instructor')"><span class="choice-icon">◉</span><span class="tag orange">Instructeur</span><h2>Piloter une session</h2><p class="muted">Lancer les questions et afficher le sondage.</p></button><button class="choice" onclick="openView('admin')"><span class="choice-icon">▦</span><span class="tag gray">Administration</span><h2>Créer un quiz</h2><p class="muted">Préparer le contenu et générer le lien.</p></button></div></section>`)}
function join(){let fromUrl=new URLSearchParams(location.search).get('session')||'';layout(`<div class="login"><p class="eyebrow">Accès apprenant</p><h1>Rejoindre la session</h1><div class="card"><label>Code de session</label><input id="joinCode" value="${esc(fromUrl)}" placeholder="Ex. THE426" maxlength="8"><label>Nom et prénom</label><input id="learnerName" placeholder="Ex. Amélie Laurent"><p class="muted">Après connexion, vous entrez dans la salle d’attente.</p><div class="actions" style="margin-top:20px"><button class="button" onclick="joinSession()">Rejoindre la salle</button><button class="button secondary" onclick="openView('landing')">Retour</button></div></div></div>`)}
function joinSession(){let key=document.querySelector('#joinCode').value.trim().toUpperCase();learnerName=document.querySelector('#learnerName').value.trim();let s=sessionByCode(key);if(!learnerName)return alert('Saisissez votre nom et prénom.');if(!s)return alert('Session introuvable. Vérifiez le QR code ou le code reçu.');if(!s.participants.includes(learnerName)&&s.participants.length<30)s.participants.push(learnerName);activeSession=s;save();openView(s.status==='live'?'learnerQuiz':'waiting')}
function waiting(){if(!activeSession)return openView('join');let s=sessionByCode(activeSession.code);layout(`<div class="login"><p class="eyebrow">Session ${esc(s.code)}</p><h1>Vous êtes dans la salle.</h1><div class="card center"><div class="waiting-ring">◌</div><h2>En attente de l’instructeur</h2><p class="muted">Le quiz « ${esc(s.title)} » démarrera lorsque l’instructeur lancera la première question.</p><span class="tag">${s.participants.length} / 30 participants</span><div class="actions" style="justify-content:center;margin-top:22px"><button class="button secondary" onclick="refreshLearner()">Actualiser</button></div></div></div>`)}
function refreshLearner(){let s=sessionByCode(activeSession?.code);openView(s?.status==='live'?'learnerQuiz':'waiting')}
function learnerQuiz(){let s=sessionByCode(activeSession?.code);if(!s||s.status!=='live')return waiting();let quiz=quizFor(s),q=quiz.questions[s.questionIndex];if(!q)return learnerEnd();answerChoice=null;layout(`<div class="question-head"><div><p class="eyebrow">${esc(s.title)}</p><h1>Question ${s.questionIndex+1} / ${quiz.questions.length}</h1></div><div class="timer" id="countdown">${q.seconds}s</div></div><div class="card" style="margin-top:20px"><p class="question">${esc(q.body)}</p><div class="answers">${q.answers.map((a,i)=>`<label class="answer"><input type="radio" name="answer" onchange="answerChoice=${i}"><span class="answer-letter">${'ABCD'[i]}</span><span>${esc(a)}</span></label>`).join('')}</div><div id="learnerFeedback"></div><div class="actions" style="margin-top:20px"><button class="button" onclick="submitAnswer()">Valider ma réponse</button></div></div>`);let left=q.seconds;timer=setInterval(()=>{left--;let e=document.querySelector('#countdown');if(e)e.textContent=`${Math.max(0,left)}s`;if(left<=0){clearInterval(timer);submitAnswer(true)}},1000)}
function submitAnswer(timeout=false){clearInterval(timer);if(answerChoice===null&&!timeout)return alert('Choisissez une proposition avant de valider.');let s=sessionByCode(activeSession.code);s.answers??={};s.answers[learnerName]=answerChoice;save();document.querySelector('#learnerFeedback').innerHTML=`<div class="feedback"><b>Réponse enregistrée.</b>${timeout?' Le temps est écoulé.':''}<br>Attendez la consigne de l’instructeur.</div>`}
function learnerEnd(){layout(`<div class="login"><p class="eyebrow">Session terminée</p><h1>Merci ${esc(learnerName)} !</h1><div class="card center"><span class="tag">Quiz complété</span><p class="muted" style="margin-top:14px">Votre participation a bien été enregistrée.</p></div></div>`)}
function instructor(){layout(`<div class="layout"><aside class="sidebar"><p>Instructeur</p><button class="nav-button active" onclick="instructorPanel('sessions',this)">Mes sessions</button><button class="nav-button" onclick="instructorPanel('pilot',this)">Pilotage live</button><button class="nav-button" onclick="openView('admin')">Créer un quiz</button></aside><section><div id="sessions" class="panel active"><p class="eyebrow">Instructeur</p><div class="row"><h1>Mes sessions</h1><button class="button" onclick="openView('admin')">+ Créer une session</button></div><div class="grid" style="margin-top:18px">${sessions.length?sessions.map(s=>`<div class="card"><div class="row"><h2>${esc(s.title)}</h2><span class="tag ${s.status==='live'?'orange':''}">${s.status==='live'?'En direct':'Prête'}</span></div><p class="muted">Code : <b>${s.code}</b> · ${s.participants.length}/30 participants</p><div class="actions" style="margin-top:15px"><button class="button" onclick="selectSession('${s.code}')">Piloter</button><button class="button secondary" onclick="copyLink('${s.code}')">Copier le lien</button></div></div>`).join(''):'<div class="card empty">Aucune session. Créez votre premier quiz depuis l’administration.</div>'}</div></div><div id="pilot" class="panel"><p class="eyebrow">Session en direct</p><h1 id="pilotTitle">Sélectionnez une session</h1><div id="pilotBody" class="card"><p class="muted">Choisissez une session dans « Mes sessions ».</p></div></div></section></div>`)}
function instructorPanel(id,b){document.querySelectorAll('.panel').forEach(e=>e.classList.toggle('active',e.id===id));if(b){document.querySelectorAll('.nav-button').forEach(e=>e.classList.remove('active'));b.classList.add('active')}}
function selectSession(key){activeSession=sessionByCode(key);instructorPanel('pilot');renderPilot()}
function renderPilot(){let s=sessionByCode(activeSession?.code);if(!s)return;let quiz=quizFor(s),q=quiz.questions[s.questionIndex]||null,answers=Object.values(s.answers||{});document.querySelector('#pilotTitle').textContent=s.title;document.querySelector('#pilotBody').innerHTML=`<div class="grid three"><div class="metric"><b>${s.participants.length}</b><span>Connectés</span></div><div class="metric"><b>${answers.length}</b><span>Réponses reçues</span></div><div class="metric"><b>${s.status==='live'?'En direct':'En attente'}</b><span>État de la session</span></div></div><hr><h2>${q?esc(q.body):'Quiz terminé'}</h2><div class="actions"><button class="button orange" onclick="startLive()">${s.status==='live'?'Relancer le minuteur':'Lancer la question'}</button><button class="button" onclick="showPoll()">Afficher le sondage</button><button class="button secondary" onclick="nextLiveQuestion()">Question suivante</button></div><div id="poll" style="margin-top:20px"></div>`}
function startLive(){let s=sessionByCode(activeSession.code);s.status='live';s.answers={};save();renderPilot()}
function nextLiveQuestion(){let s=sessionByCode(activeSession.code),quiz=quizFor(s);s.questionIndex++;s.answers={};if(s.questionIndex>=quiz.questions.length)s.status='finished';save();renderPilot()}
function showPoll(){let s=sessionByCode(activeSession.code),quiz=quizFor(s),q=quiz.questions[s.questionIndex],count=Object.values(s.answers||{}),poll=document.querySelector('#poll');if(!q)return;poll.innerHTML=`<h2>Résultats projetables</h2>${q.answers.map((a,i)=>{let n=count.filter(x=>x===i).length,p=count.length?Math.round(n/count.length*100):0;return `<div class="bar-row"><b>${'ABCD'[i]} · ${esc(a)}</b><span>${p}%</span><div class="bar"><span style="width:${p}%"></span></div></div>`}).join('')}<div class="notice">Réponse correcte : ${'ABCD'[q.correct]}. À annoncer oralement aux apprenants.</div>`}
function admin(){layout(`<div class="layout"><aside class="sidebar"><p>Administration</p><button class="nav-button active" onclick="adminPanel('create',this)">Créer une session</button><button class="nav-button" onclick="adminPanel('content',this)">Questions</button><button class="nav-button" onclick="adminPanel('settings',this)">Réglages</button></aside><section><div id="create" class="panel active"><p class="eyebrow">Étape 1</p><h1>Créer un quiz live</h1><div class="card"><p class="muted">Sélectionnez un chapitre et nommez la session. Le lien et le QR code sont créés automatiquement.</p><label>Chapitre / quiz</label><select id="sessionChapter">${data.chapters.map(c=>`<option value="${c.id}">${esc(c.title)} — ${esc(c.quiz.title)}</option>`).join('')}</select><label>Nom de la session</label><input id="sessionTitle" placeholder="Ex. Formation équipe matin"><div class="actions" style="margin-top:20px"><button class="button" onclick="createSession()">Créer et générer le QR code</button></div></div><div id="createdSession" style="margin-top:20px"></div></div><div id="content" class="panel"><p class="eyebrow">Contenu</p><div class="row"><h1>Questions par chapitre</h1><button class="button" onclick="openQuestionModal()">+ Ajouter une question</button></div><div class="card" style="margin-top:18px"><div class="tabs">${data.chapters.map((c,i)=>`<button class="tab ${i===0?'active':''}" onclick="renderQuestions('${c.id}',this)">${esc(c.title)}</button>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>Question</th><th>Temps</th><th>Réponses</th></tr></thead><tbody id="questionRows"></tbody></table></div></div></div><div id="settings" class="panel"><p class="eyebrow">Paramètres</p><h1>Barème & capacité</h1><div class="grid two"><div class="card"><h2>Examen final</h2><label>Seuil de réussite</label><input value="70 %"><label>Nombre de tentatives</label><input type="number" value="2" min="1"></div><div class="card"><h2>Sessions</h2><label>Durée par défaut</label><select><option>30 secondes</option><option>45 secondes</option><option>60 secondes</option></select><label>Capacité maximum</label><input value="30" type="number" max="30"></div></div></div></section></div>`);renderQuestions(data.chapters[0].id)}
function adminPanel(id,b){document.querySelectorAll('.panel').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('.nav-button').forEach(e=>e.classList.remove('active'));b?.classList.add('active')}
function createSession(){let chapterId=document.querySelector('#sessionChapter').value,chapter=data.chapters.find(c=>c.id===chapterId),title=document.querySelector('#sessionTitle').value.trim()||chapter.quiz.title,key=code();let s={code:key,title,chapterId,status:'waiting',questionIndex:0,participants:[],answers:{},createdAt:new Date().toISOString()};sessions.unshift(s);save();document.querySelector('#createdSession').innerHTML=`<div class="card center"><span class="tag">Session créée</span><h2 style="margin-top:10px">${esc(title)}</h2><img class="generated-qr" src="${qr(key)}" alt="QR code de la session ${key}"><div class="code">${key}</div><label>Lien automatique à partager</label><input id="generatedLink" readonly value="${esc(sessionUrl(key))}"><div class="actions" style="justify-content:center;margin-top:16px"><button class="button" onclick="copyGeneratedLink()">Copier le lien</button><button class="button secondary" onclick="openView('instructor')">Piloter cette session</button></div></div>`}
function copyGeneratedLink(){navigator.clipboard?.writeText(document.querySelector('#generatedLink').value);alert('Lien copié.')}
function copyLink(key){navigator.clipboard?.writeText(sessionUrl(key));alert('Lien copié.')}
function renderQuestions(id,b){if(b){document.querySelectorAll('.tab').forEach(e=>e.classList.remove('active'));b.classList.add('active')}let c=data.chapters.find(c=>c.id===id),el=document.querySelector('#questionRows');if(!el)return;el.innerHTML=c.quiz.questions.map(q=>`<tr><td>${esc(q.body)}</td><td>${q.seconds} s</td><td>A · B · C · D</td></tr>`).join('')}
// runtime bindings
function openQuestionModal(){app.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="card"><div class="row"><h2>Ajouter une question</h2><button class="button secondary" onclick="closeModal()">Fermer</button></div><label>Chapitre</label><select id="newChapter">${data.chapters.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select><label>Question</label><textarea id="newBody"></textarea><div class="form-grid"><div><label>Temps</label><input id="newSeconds" type="number" min="5" value="30"></div><div><label>Bonne réponse</label><select id="newCorrect"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></div></div>${['A','B','C','D'].map((l,i)=>`<label>Proposition ${l}<input id="newAnswer${i}"></label>`).join('')}<label>Explication</label><textarea id="newExplanation"></textarea><div class="actions" style="margin-top:20px"><button class="button" onclick="saveQuestion()">Enregistrer</button></div></div></div>`)}
function closeModal(){document.querySelector('#modal')?.remove()}
function saveQuestion(){let body=document.querySelector('#newBody').value.trim(),answers=[0,1,2,3].map(i=>document.querySelector('#newAnswer'+i).value.trim());if(!body||answers.some(x=>!x))return alert('Renseignez la question et les quatre propositions.');let c=data.chapters.find(c=>c.id===document.querySelector('#newChapter').value);c.quiz.questions.push({id:'q'+Date.now(),body,seconds:Number(document.querySelector('#newSeconds').value)||30,answers,correct:Number(document.querySelector('#newCorrect').value),explanation:document.querySelector('#newExplanation').value||'Réponse enregistrée.'});save();closeModal();renderQuestions(c.id)}
Object.assign(window,{openView,joinSession,refreshLearner,submitAnswer,instructorPanel,selectSession,startLive,nextLiveQuestion,showPoll,adminPanel,createSession,copyGeneratedLink,copyLink,renderQuestions,openQuestionModal,closeModal,saveQuestion});
bus?.addEventListener('message',()=>{sessions=JSON.parse(localStorage.getItem(sessionsKey)||'[]')});
landing();

// Gestion des quiz/sessions créés depuis l'administration.
const originalAdminView = admin;
const originalCreateSession = createSession;
admin = () => { originalAdminView(); renderAdminSessions(); };
createSession = () => { originalCreateSession(); renderAdminSessions(); };
function renderAdminSessions(){
  const panel = document.querySelector('#create');
  if (!panel) return;
  document.querySelector('#scheduledSessions')?.remove();
  const rows = sessions.length ? sessions.map(session => `
    <tr><td><b>${esc(session.title)}</b><br><small>${session.code}</small></td><td>${esc(data.chapters.find(c=>c.id===session.chapterId)?.title||'')}</td><td><span class="tag ${session.status==='live'?'orange':''}">${session.status==='live'?'En direct':'Prête'}</span></td><td><button class="button danger" onclick="deleteQuizSession('${session.code}')">Supprimer</button></td></tr>`).join('') : '<tr><td colspan="4" class="empty">Aucun quiz programmé.</td></tr>';
  panel.insertAdjacentHTML('beforeend', `<div id="scheduledSessions" class="card" style="margin-top:20px"><div class="row"><h2>Quiz programmés</h2><span class="tag gray">${sessions.length}</span></div><div class="table-wrap"><table><thead><tr><th>Quiz / code</th><th>Chapitre</th><th>État</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></div>`);
}
function deleteQuizSession(sessionCode){
  const session = sessionByCode(sessionCode);
  if (!session || !confirm(`Supprimer définitivement le quiz programmé « ${session.title} » ?`)) return;
  sessions = sessions.filter(item => item.code !== sessionCode);
  if (activeSession?.code === sessionCode) activeSession = null;
  save();
  admin();
}
Object.assign(window, { createSession, deleteQuizSession });

// Authentification Supabase pour les opérations d'administration.
const authenticatedAdminView = admin;
const localQuestionSave = saveQuestion;
admin = () => {
  if (!getSession()) return showAdminLogin();
  authenticatedAdminView();
  document.querySelector('.sidebar')?.insertAdjacentHTML('beforeend', '<button class="nav-button" onclick="logoutAdmin()">Déconnexion</button>');
};
function showAdminLogin(){
  app.insertAdjacentHTML('beforeend', `<div class="modal" id="adminLogin"><div class="card"><div class="row"><h2>Connexion administration</h2><button class="button secondary" onclick="closeAdminLogin()">Fermer</button></div><p class="muted">Utilisez le compte superadmin créé dans Supabase Auth.</p><label>Email</label><input id="adminEmail" type="email" autocomplete="email"><label>Mot de passe</label><input id="adminPassword" type="password" autocomplete="current-password"><div id="loginError" class="notice hidden" style="margin-top:14px"></div><div class="actions" style="margin-top:20px"><button class="button" onclick="loginAdmin()">Se connecter</button></div></div></div>`);
}
function closeAdminLogin(){document.querySelector('#adminLogin')?.remove()}
async function loginAdmin(){
  const email=document.querySelector('#adminEmail').value.trim(), password=document.querySelector('#adminPassword').value;
  const error=document.querySelector('#loginError');
  if(!email||!password){error.textContent='Renseignez votre email et votre mot de passe.';error.classList.remove('hidden');return;}
  try { await signIn(email,password); closeAdminLogin(); authenticatedAdminView(); }
  catch (e) { error.textContent=e.message; error.classList.remove('hidden'); }
}
function logoutAdmin(){signOut(); openView('landing')}

saveQuestion = async () => {
  if (!getSession()) return showAdminLogin();
  const body=document.querySelector('#newBody').value.trim();
  const answers=[0,1,2,3].map(i=>document.querySelector('#newAnswer'+i).value.trim());
  if(!body||answers.some(answer=>!answer)) return alert('Renseignez la question et les quatre propositions.');
  const chapter=data.chapters.find(item=>item.id===document.querySelector('#newChapter').value);
  const question={
    id:'q'+Date.now(), body,
    seconds:Number(document.querySelector('#newSeconds').value)||30,
    answers,
    correct:Number(document.querySelector('#newCorrect').value),
    explanation:document.querySelector('#newExplanation').value||'Réponse enregistrée.',
    position:chapter.quiz.questions.length
  };
  try {
    await createQuestion(data.chapters.indexOf(chapter), question);
    chapter.quiz.questions.push(question);
    save(); closeModal(); renderQuestions(chapter.id);
    alert('Question et quatre propositions enregistrées dans Supabase.');
  } catch(error) {
    alert(`La question n’a pas été enregistrée dans Supabase : ${error.message}`);
  }
};
Object.assign(window,{admin,showAdminLogin,closeAdminLogin,loginAdmin,logoutAdmin,saveQuestion});
