import {getSession,signIn,signOut,createQuestion,getCatalog,getInstructorProfile,createLiveSession,getLiveSessions,updateLiveSession,rpc} from './supabase-api.js';
const app=document.querySelector('#app'),ck='ts-hepa-content-v3',sk='ts-hepa-sessions-v3';
const seed={theme:'Filtres THE/HEPA',chapters:[{id:'the',theme:'Filtres THE/HEPA',title:'Principes THE',quiz:{title:'Quiz THE',questions:[{id:'q1',body:'Quel est l’objectif principal d’un filtre THE/HEPA ?',seconds:30,answers:['Réduire le bruit','Retenir les particules','Augmenter le débit','Refroidir'],correct:1}]}},{id:'integrity',theme:'Filtres THE/HEPA',title:'Essais d’intégrité',quiz:{title:'Quiz intégrité',questions:[{id:'q2',body:'Pourquoi faire un essai d’intégrité ?',seconds:35,answers:['Couleur','Détecter les fuites','Bruit','Nettoyage'],correct:1}]}}]};
let data=JSON.parse(localStorage.getItem(ck)||'null')||seed,sessions=JSON.parse(localStorage.getItem(sk)||'[]');
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{localStorage.setItem(ck,JSON.stringify(data));localStorage.setItem(sk,JSON.stringify(sessions))};
const themes=()=>[...new Set(data.chapters.map(c=>c.theme||data.theme))];
const qr=code=>`https://api.qrserver.com/v1/create-qr-code/?size=220&data=${encodeURIComponent(`${location.origin}${location.pathname.replace(/[^/]*$/,'')}learner.html?session=${code}`)}`;
function shell(body){app.innerHTML=`<header class="topbar"><a class="brand" href="./instructor.html"><span class="logo">TS</span>Formation <small>· Instructeur</small></a><a class="link-button" href="./learner.html">🎓 Apprenant</a></header><main class="container animate-in">${body}</main>`}
function login(){shell(`<div class="login"><p class="eyebrow">Accès instructeur</p><h1>Connexion</h1><div class="card"><label>Email</label><input id="email" type="email"><label>Mot de passe</label><input id="password" type="password"><p><button class="button" onclick="doLogin()">Se connecter →</button></p><p id="error" class="notice hidden"></p></div></div>`)}
async function doLogin(){try{await signIn(email.value,password.value);render()}catch(e){error.textContent=e.message;error.classList.remove('hidden')}}
function render(){if(!getSession())return login();shell(`<div class="layout"><aside class="sidebar"><p>Navigation</p><button class="nav-button active" onclick="showPanel('sessions',this)">📡 Sessions live</button><button class="nav-button" onclick="showPanel('questions',this)">🧩 Questions</button><button class="nav-button" onclick="showPanel('scheduled',this)">🗓️ Quiz programmés</button><button class="nav-button" onclick="showPanel('performance',this)">🏆 Performances</button><button class="nav-button" onclick="showPanel('settings',this)">⚙️ Réglages</button><button class="nav-button" onclick="logout()">↪ Déconnexion</button></aside><section><div id="sessions" class="panel active"><p class="eyebrow">Créer et diffuser</p><h1>Nouvelle session live <span class="spark">✦</span></h1><div class="card"><label>Thème · chapitre</label><select id="sessionChapter">${data.chapters.map(c=>`<option value="${c.id}">${esc(c.theme)} · ${esc(c.title)}</option>`).join('')}</select><label>Nom de la session</label><input id="sessionTitle" placeholder="Ex. Formation équipe matin"><p><button class="button" onclick="newSession()">Générer le QR code ✨</button></p></div><div id="createdSession"></div></div><div id="questions" class="panel"><div class="row"><div><p class="eyebrow">Bibliothèque</p><h1>Questions par thème</h1></div><button class="button" onclick="questionModal()">＋ Ajouter une question</button></div><div class="tabs theme-tags">${themes().map((t,i)=>`<button class="tab ${i?'':'active'}" onclick="selectTheme('${esc(t)}',this)">🏷️ ${esc(t)}</button>`).join('')}</div><div id="accordions" class="accordion-list"></div></div><div id="scheduled" class="panel"><div class="row"><h1>Quiz programmés</h1><button class="button secondary" onclick="exportXls()">⇩ Exporter Excel</button></div><div class="card table-wrap"><table><thead><tr><th>Quiz/code</th><th>Thème</th><th>Chapitre</th><th>État</th><th>Actions</th></tr></thead><tbody>${sessionRows()}</tbody></table></div></div><div id="performance" class="panel"><h1>Performances individuelles</h1><select id="perf" onchange="performance()"><option value="">Sélectionner une session</option>${sessions.map(s=>`<option value="${s.code}">${esc(s.title)}</option>`).join('')}</select><div id="perfRows" class="card" style="margin-top:18px">Sélectionnez une session.</div></div><div id="settings" class="panel"><h1>⚙️ Réglages</h1><div class="grid two"><div class="card"><span class="icon-orb">🎯</span><h2>Évaluation</h2><label>Seuil</label><input value="70 %"></div><div class="card"><span class="icon-orb">👥</span><h2>Session</h2><label>Capacité</label><input value="30"></div></div></div></section></div>`);selectTheme(themes()[0])}
function showPanel(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));b?.classList.add('active')}
function selectTheme(t,b){document.querySelectorAll('.theme-tags .tab').forEach(x=>x.classList.remove('active'));b?.classList.add('active');accordions.innerHTML=data.chapters.filter(c=>c.theme===t).map(c=>`<details class="chapter-accordion"><summary><span class="chapter-icon">📚</span><span><b>${esc(c.title)}</b><small>${c.quiz.questions.length} question(s)</small></span><span class="chevron">⌄</span></summary><div class="chapter-content">${c.quiz.questions.map((q,i)=>`<article class="question-row"><span class="question-number">${i+1}</span><div><b>${esc(q.body)}</b><p>⏱ ${q.seconds}s · 4 propositions</p></div></article>`).join('')||'<p class="muted">Aucune question.</p>'}</div></details>`).join('')}
function questionModal(){app.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="card"><div class="row"><h2>🧩 Ajouter une question</h2><button class="button secondary" onclick="closeModal()">Fermer</button></div><div class="form-grid"><div><label>Thème existant</label><select id="newTheme" onchange="chaptersForTheme()">${themes().map(t=>`<option>${esc(t)}</option>`).join('')}</select></div><div><label>Nouveau thème</label><input id="newThemeName"></div><div><label>Chapitre existant</label><select id="newChapter"></select></div><div><label>Nouveau chapitre</label><input id="newChapterName"></div></div><label>Question</label><textarea id="body"></textarea><div class="form-grid"><div><label>Temps</label><input id="seconds" value="30" type="number"></div><div><label>Bonne réponse</label><select id="correct"><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></div></div>${[0,1,2,3].map((_,i)=>`<label>Proposition ${'ABCD'[i]}<input id="answer${i}"></label>`).join('')}<p><button class="button" onclick="saveQuestion()">Enregistrer ✨</button></p></div></div>`);chaptersForTheme()}
function chaptersForTheme(){newChapter.innerHTML=data.chapters.filter(c=>c.theme===newTheme.value).map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}
async function saveQuestion(){const answers=[0,1,2,3].map(i=>document.querySelector('#answer'+i).value.trim()),body=document.querySelector('#body').value.trim();if(!body||answers.some(x=>!x))return alert('Complétez la question et les quatre propositions.');let c=data.chapters.find(x=>x.id===newChapter.value),name=newChapterName.value.trim(),theme=newThemeName.value.trim()||newTheme.value;if(name){c={id:'local-'+Date.now(),theme,title:name,quiz:{title:name,questions:[]}};data.chapters.push(c)}const q={id:'q'+Date.now(),body,seconds:+seconds.value||30,answers,correct:+correct.value};if(c.id.startsWith('local-')){c.quiz.questions.push(q);save();closeModal();return render()}try{await createQuestion(data.chapters.indexOf(c),q);c.quiz.questions.push(q);save();closeModal();render();alert('Question enregistrée dans Supabase.')}catch(e){alert(e.message)}}
function closeModal(){modal?.remove()}
function newSession(){const c=data.chapters.find(x=>x.id===sessionChapter.value),s={code:code(),title:sessionTitle.value.trim()||c.quiz.title,chapterId:c.id,status:'waiting',participants:[],answers:{},answerHistory:{},questionIndex:0};sessions.unshift(s);save();createdSession.innerHTML=`<div class="card center pop-in" style="margin-top:18px"><span class="tag">Session créée</span><h2>${esc(s.title)}</h2><img class="generated-qr" src="${qr(s.code)}"><div class="code">${s.code}</div><label>Lien apprenant</label><input readonly value="${location.origin}${location.pathname.replace(/[^/]*$/,'')}learner.html?session=${s.code}"></div>`}
function code(){return 'THE'+Math.random().toString(36).slice(2,5).toUpperCase()}
function sessionRows(){return sessions.map(s=>{const c=data.chapters.find(x=>x.id===s.chapterId);return `<tr><td><b>${esc(s.title)}</b><br><small>${s.code}</small></td><td>${esc(c?.theme)}</td><td>${esc(c?.title)}</td><td><span class="tag">${s.status}</span></td><td><button class="button danger" onclick="del('${s.code}')">Supprimer</button></td></tr>`}).join('')||'<tr><td colspan="5">Aucun quiz programmé.</td></tr>'}
function del(k){if(confirm('Supprimer cette session ?')){sessions=sessions.filter(s=>s.code!==k);save();render()}}
function exportXls(){const a=document.createElement('a'),html=`<table>${sessions.map(s=>`<tr><td>${esc(s.title)}</td><td>${s.code}</td></tr>`).join('')}</table>`;a.href=URL.createObjectURL(new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'}));a.download='quiz-programmes.xls';a.click()}
function performance(){const s=sessions.find(x=>x.code===perf.value);perfRows.innerHTML=s?`<p>${s.participants.length} apprenant(s) enregistré(s).</p>`:'Sélectionnez une session.'}
function logout(){signOut();login()}
Object.assign(window,{doLogin,showPanel,selectTheme,questionModal,chaptersForTheme,saveQuestion,closeModal,newSession,del,exportXls,performance,logout});render();
const initialRender=render;render=()=>{initialRender();document.querySelectorAll('#scheduled tbody tr').forEach((row,i)=>{if(!sessions[i])return;row.lastElementChild.insertAdjacentHTML('afterbegin',`<button class="button" onclick="startSession('${sessions[i].code}')">${sessions[i].status==='live'?'En direct':'Lancer'}</button> `)})};
function startSession(key){const s=sessions.find(x=>x.code===key);s.status='live';s.endsAt=Date.now()+(data.chapters.find(c=>c.id===s.chapterId)?.quiz.questions[s.questionIndex]?.seconds||30)*1000;save();render();showPanel('scheduled')}
Object.assign(window,{startSession});render();

// Pilotage connecté à Supabase : mêmes données pour l'instructeur et les apprenants.
let remoteSessions=[];
const legacyRender=render;
render=async()=>{legacyRender();const sidebar=document.querySelector('.sidebar');if(!sidebar)return;sidebar.insertAdjacentHTML('beforeend','<button class="nav-button" onclick="openPilot()">🎮 Piloter le quiz</button>');document.querySelector('.layout section').insertAdjacentHTML('beforeend','<div id="pilot" class="panel"><p class="eyebrow">Contrôle direct</p><h1>Piloter le quiz</h1><div id="pilotContent" class="card">Chargement…</div></div>')};
async function newSession(){try{const catalog=await getCatalog(),profile=await getInstructorProfile(),flat=catalog.flatMap(t=>(t.chapters||[]).map(c=>({theme:t,chapter:c,quiz:Array.isArray(c.quizzes)?c.quizzes[0]:c.quizzes}))),selected=data.chapters.findIndex(c=>c.id===sessionChapter.value),item=flat[selected];if(!item?.quiz)throw new Error('Quiz Supabase introuvable.');const live=await createLiveSession({code:code(),quiz_id:item.quiz.id,instructor_id:profile.id,status:'waiting'});sessions.unshift({id:live.id,code:live.code,title:sessionTitle.value.trim()||item.quiz.title,chapterId:sessionChapter.value,status:'waiting',questionIndex:0,questionIds:(item.quiz.questions||[]).sort((a,b)=>a.position-b.position).map(q=>q.id)});save();createdSession.innerHTML=`<div class="card center pop-in" style="margin-top:18px"><span class="tag">Session créée</span><h2>${esc(sessionTitle.value||item.quiz.title)}</h2><img class="generated-qr" src="${qr(live.code)}"><div class="code">${live.code}</div><label>Lien apprenant</label><input readonly value="${location.origin}${location.pathname.replace(/[^/]*$/,'')}learner.html?session=${live.code}"></div>`}catch(e){alert(e.message)}}
async function openPilot(){showPanel('pilot');try{remoteSessions=await getLiveSessions();document.querySelector('#pilotContent').innerHTML=remoteSessions.length?remoteSessions.map(s=>`<article class="question-row"><span class="question-number">🎮</span><div style="flex:1"><b>${esc(s.code)}</b><p>${esc(s.status)} · ${s.session_participants?.filter(p=>p.status==='joined').length||0} accepté(s)</p><div class="actions"><button class="button" onclick="pilotStart('${s.id}')">Lancer / reprendre</button><button class="button secondary" onclick="pilotPause('${s.id}')">Pause</button><button class="button secondary" onclick="pilotNext('${s.id}')">Suivant</button><button class="button danger" onclick="pilotFinish('${s.id}')">Terminer</button></div><div>${(s.session_participants||[]).filter(p=>p.status==='waiting_list').map(p=>`<button class="button secondary" onclick="approve('${p.id}')">✓ Accepter ${esc(p.app_users?.first_name||'apprenant')}</button>`).join('')}</div></div></article>`).join(''):'Aucune session Supabase.'}catch(e){document.querySelector('#pilotContent').textContent=e.message}}
async function pilotStart(id){const s=remoteSessions.find(x=>x.id===id),local=sessions.find(x=>x.id===id),qid=local?.questionIds?.[local.questionIndex||0];if(!qid)return alert('Questions Supabase indisponibles pour cette session.');await updateLiveSession(id,{status:'live',current_question_id:qid,question_started_at:new Date().toISOString(),question_ends_at:new Date(Date.now()+30000).toISOString()});openPilot()}
async function pilotPause(id){await updateLiveSession(id,{status:'polling'});openPilot()}
async function pilotNext(id){const local=sessions.find(x=>x.id===id);if(!local)return;local.questionIndex=(local.questionIndex||0)+1;save();if(local.questionIndex>=local.questionIds.length)return pilotFinish(id);await updateLiveSession(id,{status:'waiting',current_question_id:null,question_started_at:null,question_ends_at:null});openPilot()}
async function pilotFinish(id){await updateLiveSession(id,{status:'finished',ended_at:new Date().toISOString()});openPilot()}
async function approve(id){await rpc('approve_live_participant',{p_participant_id:id});openPilot()}
Object.assign(window,{newSession,openPilot,pilotStart,pilotPause,pilotNext,pilotFinish,approve});render();

selectTheme=(theme,button)=>{document.querySelectorAll('.theme-tags .tab').forEach(x=>x.classList.remove('active'));button?.classList.add('active');const box=document.querySelector('#accordions');if(!box)return;box.innerHTML=data.chapters.filter(c=>c.theme===theme).map(c=>`<details class="chapter-accordion"><summary><span class="chapter-icon">📚</span><span><b>${esc(c.title)}</b><small>${c.quiz.questions.length} question(s)</small></span><span class="chevron">⌄</span></summary><div class="chapter-content">${c.quiz.questions.map((q,i)=>`<article class="question-row"><span class="question-number">${i+1}</span><div style="flex:1"><b>${esc(q.body)}</b><div class="answer-preview">${q.answers.map((a,j)=>`<button class="answer-chip" onclick="editAnswer('${c.id}','${q.id}',${j})">${'ABCD'[j]} · ${esc(a)} <span title="Modifier">✏️</span></button>`).join('')}</div></div></article>`).join('')}</div></details>`).join('')};
function editAnswer(chapterId,questionId,index){const q=data.chapters.find(c=>c.id===chapterId)?.quiz.questions.find(q=>q.id===questionId),value=prompt(`Modifier la proposition ${'ABCD'[index]}`,q.answers[index]);if(value?.trim()){q.answers[index]=value.trim();save();selectTheme(data.chapters.find(c=>c.id===chapterId).theme)}}
Object.assign(window,{selectTheme,editAnswer});
performance=async()=>{const key=document.querySelector('#perf').value,box=document.querySelector('#perfRows');if(!key)return;try{const rows=await getLiveSessions(),s=rows.find(x=>x.code===key);if(!s)return;const people=s.session_participants||[],answers=s.live_answers||[];box.innerHTML=`<table><thead><tr><th>Apprenant</th><th>Statut</th><th>Réponses envoyées</th></tr></thead><tbody>${people.map(p=>`<tr><td>${esc(p.app_users?.first_name)} ${esc(p.app_users?.last_name)}</td><td>${esc(p.status)}</td><td>${answers.filter(a=>a.participant_id===p.id).length}</td></tr>`).join('')}</tbody></table>`}catch(e){box.textContent=e.message}};
const performanceRender=render;
render=async()=>{await performanceRender();const select=document.querySelector('#perf');if(select)select.onchange=performance};
render();
