import { signInAnonymously, rpc } from './supabase-api.js';
const app=document.querySelector('#app'),requested=new URLSearchParams(location.search).get('session')||'';
let code='',poller=null,submitted=false;
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function screen(body){app.innerHTML=`<div class="learner-shell animate-in"><header class="learner-header"><span>🎓 TS Formation</span><small>Quiz THE/HEPA</small></header><main class="learner-main">${body}</main></div>`}
function join(){screen(`<div class="login"><p class="eyebrow">Bienvenue</p><h1>Rejoindre la session</h1><div class="card"><span class="icon-orb">📱</span><label>Nom</label><input id="first" placeholder="Prénom"><label>Prénom</label><input id="last" placeholder="Nom"><label>Code de session</label><input id="code" value="${esc(requested)}"><p><button class="button" onclick="enter()">Entrer dans la salle d’attente →</button></p></div></div>`)}
async function enter(){const first=document.querySelector('#first').value.trim(),last=document.querySelector('#last').value.trim();code=document.querySelector('#code').value.trim().toUpperCase();if(!first||!last||!code)return alert('Renseignez nom, prénom et code.');try{await signInAnonymously();await rpc('join_live_by_code',{p_code:code,p_first_name:first,p_last_name:last});waiting();poller=setInterval(refresh,1000)}catch(e){alert(e.message.includes('Anonymous')?'Activez Anonymous sign-ins dans Supabase Auth puis réessayez.':e.message)}}
function waiting(){screen(`<div class="login center"><p class="eyebrow">Salle d’attente</p><div class="card"><div class="waiting-animation"><span></span><span></span><span></span></div><h1>Demande envoyée</h1><p class="muted">Votre instructeur doit accepter votre participation. Vous serez dirigé·e automatiquement vers le quiz.</p><span class="tag">⌛ En attente de validation</span></div></div>`)}
async function refresh(){try{const state=await rpc('live_learner_state',{p_code:code});if(!state)return;if(state.participant_status==='joined'&&state.status==='live'&&state.question)question(state);else if(state.status==='finished'){clearInterval(poller);screen('<div class="login center"><div class="card"><h1>Quiz terminé 🎉</h1><p>Merci pour votre participation.</p></div></div>')}}catch(e){console.error(e)}}
function question(state){const q=state.question;if(document.querySelector('#questionId')?.value===q.id)return;submitted=false;screen(`<div class="login"><input type="hidden" id="questionId" value="${q.id}"><div class="question-head"><h1>Question ${q.position+1}</h1><div id="timer" class="timer"></div></div><div class="card"><p class="question">${esc(q.body)}</p><div class="answers">${q.options.map(o=>`<label class="answer"><input type="radio" name="answer" value="${o.id}"><span class="answer-letter">${o.label}</span>${esc(o.body)}</label>`).join('')}</div><div id="feedback"></div><p><button id="validate" class="button" onclick="answer()">Valider ma réponse</button></p></div></div>`);const tick=()=>{const left=Math.max(0,Math.ceil((new Date(state.question_ends_at)-Date.now())/1000));const el=document.querySelector('#timer');if(el)el.textContent=left+'s';if(left<=0){clearInterval(clock);lock('Le temps est écoulé.')}};const clock=setInterval(tick,400);tick()}
async function answer(){if(submitted)return;const option=document.querySelector('input[name=answer]:checked');if(!option)return alert('Choisissez une proposition.');try{await rpc('submit_live_answer',{p_code:code,p_option_id:option.value});submitted=true;lock('Réponse enregistrée. Attendez la question suivante.')}catch(e){lock(e.message)}}
function lock(message){document.querySelectorAll('input[name=answer]').forEach(x=>x.disabled=true);const b=document.querySelector('#validate');if(b){b.disabled=true;b.textContent='Réponse validée'}const f=document.querySelector('#feedback');if(f)f.innerHTML=`<div class="feedback">${esc(message)}</div>`}
Object.assign(window,{enter,answer});join();
